version: "3.8"
services:
  client:
    build: ./client
    volumes:
      - "./client:/app:delegated"
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react-app-container
    ports:
      - '3000:3000'